FROM node:22-alpine as frontend-builder

COPY ./Frontend /app  

WORKDIR /app

RUN npm install

RUN npm run build

FROM node:22-alpine

COPY ./Backend /app

WORKDIR /app

RUN npm install

COPY --FROM = frontend-builder /app/dist /app/public

CMD ["node","server.js"]